### ISSUE TITLE
remove rocket-specific import/logic

### ISSUE THREAD

**Issue by jonboulle** [appc/docker2aci#11]
docker2aci should not have any dependency on code in coreos/rocket; instead we should see the inverse, where tools like Rocket leverage docker2aci to fetch/run Docker images (e.g. https://github.com/coreos/rocket/issues/145). So this ticket is to track the removal of the [current dependency](https://github.com/appc/docker2aci/blob/bb72ee53c79f7c863a694a306ab47fe22fb80e5f/main.go#L10) within the docker2aci CLI on a Rocket package.

It's possible that rather than removing the _import_ feature of docker2aci entirely, it could instead move to a more generic model - for example, the ACI Registry proposed in https://github.com/coreos/rocket/pull/464. I will leave that to the implementer to explore; the main point here is that the Rocket dep goes away  :-)

**Comment by iaguis** [comment]
I'd rather remove it completely, docker2aci should not be concerned with importing.

**Comment by jonboulle** [comment]
Sgtm
Am 11.02.2015 04:41 schrieb "Iago López Galeiras" <notifications@github.com
