### ISSUE TITLE
Allow selecting the compression method

### ISSUE THREAD

**Issue by kamalmarhubi** [appc/docker2aci#110]
The [ACI spec](https://github.com/appc/spec/blob/0875c991a496fe2b65ed296551c667b199a6bfb8/spec/aci.md#image-archives) says

> Image archives MAY be compressed with gzip, bzip2, or xz.

It would be handy if the docker2aci CLI could let the user choose the compression method.

**Comment by kamalmarhubi** [comment]
I'm throwing together a PR that at least makes compression optional, adding a `--compression` flag. Neither bzip2 nor xz have compressors in the standard library, so I'll leave the allowed options as `none` and `gzip` (default).

**Comment by iaguis** [comment]
Fixed via #111
