### ISSUE TITLE
ENTRYPOINT CMD info is lost after conversion

### ISSUE THREAD

**Issue by yifan-gu** [appc/docker2aci#122]
As ENTRYPOINT and CMD are appended to construct Exec [1]. So after conversion, we cannot tell which part is the ENTRYPOINT, and which is the CMD. This creates a problem when users expect to substitute only the CMD in k8s [2].

Some solutions came out of my mind:
- Change the spec to match docker. (I am kinda reluctant to do this until we really feel this is a valid usecase).
- Write down the ENTRYPOINT and CMD during conversion in annotations, so image consumers can use the annotation to reconstruct the ENTRYPOINT and CMD.

[1] https://github.com/appc/docker2aci/blob/783b6b1c6e031c30dda7f54c47fad5ad0788e1e3/lib/common/common.go#L448-L449
[2] https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/rkt/notes.md#doesnt-support-entrypoint--cmd-feature

cc @iaguis @alban

**Comment by jonboulle** [comment]
> Write down the ENTRYPOINT and CMD during conversion in annotations, so image consumers can use the annotation to reconstruct the ENTRYPOINT and CMD.

This seems more reasonable to me for now.

**Comment by yifan-gu** [comment]
@jonboulle SGTM. I will work on a patch today.

cc @sjpotter
