### ISSUE TITLE
please tag formal releases

### ISSUE THREAD

**Issue by onlyjob** [appc/docker2aci#127]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also

 * https://en.wikipedia.org/wiki/Software_versioning
 * http://semver.org/

**Comment by iaguis** [comment]
I've been meaning to do releases for some time now but I kept putting it off.

Thanks for the reminder, I'll prepare the first release :)

**Comment by onlyjob** [comment]
Excellent. Thank you. :)

**Comment by iaguis** [comment]
https://github.com/appc/docker2aci/releases/tag/v0.9.0 :)
