### ISSUE TITLE
set default exec from ENTRYPOINT and CMD

### ISSUE THREAD

**Issue by jonboulle** [appc/docker2aci#14]
Dockerfiles have two parameters controlling what gets executed: [`ENTRYPOINT`](https://docs.docker.com/reference/builder/#entrypoint) and [`CMD`](https://docs.docker.com/reference/builder/#cmd). There is a somewhat complicated relationship between the two as they both support _exec_ and _shell_ forms and `CMD` has a third form which just results in being passed as arguments to `ENTRYPOINT`.
 
We should just follow the same logic that Docker does for resolving these into the actual default command line to be executed, and then set that as the app.exec.cmd in our created image manifest.

**Comment by iaguis** [comment]
As far as I understand, these docs you link and all the mess with _exec_ and _shell_ is only taken into account when building a docker image. By the time the image is generated, `Entrypoint` and `Cmd` are always [arrays of strings](https://github.com/docker/docker/blob/d14751bf30a70abe7bc6048af61848eed32ca140/runconfig/config.go#L28).

When running the container, it seems they just use the Entrypoint and then the Cmd as arguments or only the Cmd if the Entrypoint is not present: [daemon.getEntrypointAndArgs](https://github.com/docker/docker/blob/d14751bf30a70abe7bc6048af61848eed32ca140/daemon/daemon.go#L596).

Therefore, I think a simple `Exec := append(Entrypoint, Cmd...)` should work for our purposes.

There's still a problem with some images that don't use absolute paths for the Entrypoint, which is not allowed by the [SPEC.md](https://github.com/appc/spec/blob/28f4e29213bc8b9d105e59697c398d40138bf8ea/SPEC.md) and would require going through the image contents to get the absolute path.

**Comment by iaguis** [comment]
When the resulting command (Entrypoint+Cmd) is not absolute, we could fall back to running `/bin/sh -c command` so that the final command is absolute and will use `$PATH` to resolve command's location.

Pull Request: #20
