### ISSUE TITLE
docker i386 images can't be converted (arch 386 v. i386)

### ISSUE THREAD

**Issue by djtm** [appc/docker2aci#145]
When I try to convert any image created on an i386 machine with docker (v. 1.6), conversion fails. It says "_386_" is not a valid architecture, only "_**i**386_" is. When I create the same image on amd64, it works. And while docker seems to mark the container arch, it doesn't actually check it. I can start containers from any arch on any system with docker. They just fail to run.

**Comment by djtm** [comment]
`prepare: error finding images: error building layer: error generating ACI: error writing ACI: error writing manifest: json: error calling MarshalJSON for type schema.ImageManifest: json: error calling MarshalJSON for type types.Labels: bad arch "386" for linux (must be one of: [amd64 i386 aarch64 aarch64_be armv6l armv7l armv7b])`
The solution might be as simple as this:
[arch-386.patch.txt](https://github.com/appc/docker2aci/files/190509/arch-386.patch.txt)

**Comment by lucab** [comment]
Tracking via https://github.com/appc/docker2aci/issues/195.

**Comment by djtm** [comment]
you're welcome.
