### ISSUE TITLE
Download layers in parallel?

### ISSUE THREAD

**Issue by yifan-gu** [appc/docker2aci#146]
Pulling time comparison with `docker pull` (using nginx image, size = 188MiB when unextracted)

time (rkt 1.2.1) | time (Docker 1.9.1)
-----------|--------------
real	0m26.442s, user	0m9.496s, sys	0m1.220s | real	0m15.368s, user	0m0.060s, sys	0m0.008s

Apparently Docker is pulling the layers in parallel, while docker2aci is doing it in serial. Can we parallelize the process to speed it up?

**Comment by krnowak** [comment]
This will probably require some extra gimmicks to draw several progress bars at the same time.

**Comment by jonboulle** [comment]
#83

**Comment by jonboulle** [comment]
@dgonyeo how do you feel about tackling this?

**Comment by dgonyeo** [comment]
Sure thing.

**Comment by dgonyeo** [comment]
Status update on this: finished the work to pull things in parallel (it's [here](https://github.com/dgonyeo/docker2aci/commit/5d2b695416ea36560c8c59efec29935f63e8f42a) for the curious), need to go rewrite ioprogress to get the output to look reasonable. This is gonna be a crazy week at school, so probably won't get to that until later this week / early next week.

**Comment by jonboulle** [comment]
Fixed by #158
