### ISSUE TITLE
GID is set to root when GID is missing

### ISSUE THREAD

**Issue by yifan-gu** [appc/docker2aci#175]
When GID is empty, we use the root GID today: https://github.com/appc/docker2aci/blob/4e051449c0079ba8df59a51c14b7d310de1830b8/lib/internal/internal.go#L466

However this is not great, we should look up the GID from the /etc/passwd file in that image.

Ref:
https://github.com/appc/spec/issues/623
https://github.com/kubernetes/kubernetes/pull/27200

cc @iaguis @alban

**Comment by yifan-gu** [comment]
We might want to prioritize this one as it causes some security concerns. cc @jonboulle @philips

**Comment by jonboulle** [comment]
@yifan-gu are you able to work on it or do you need us to find someone?

**Comment by yifan-gu** [comment]
@jonboulle Not right now, so if someone can work on it, it would be great!

**Comment by lucab** [comment]
Alternative default which doesn't require looking into `/etc/passwd` (which may not be there or constructed in a malicious way): fallback to `gid=uid` when uid is specified but gid isn't. Have this been considered before?

**Comment by jonboulle** [comment]
Seems reasonable to me.
