### ISSUE TITLE
OCI: use v0.5.0 media-types

### ISSUE THREAD

**Issue by philips** [appc/docker2aci#196]
OCI v0.5.0 will change media-types. This is unreleased but is likely to be released in the next 7-10 days.

**Comment by lucab** [comment]
@vishvananda this was initially part of your PR #200 but got dropped before the final merge. What was the reason for that?

**Comment by vishvananda** [comment]
Thanks, I just missed the commit in a rebase. There is a new pr with the 1.0.0-rc1 media types. I'll add another one when rc2 comes out.
