### ISSUE TITLE
Missing ENTRYPOINT and CMD annotations in manifest with newer Docker versions

### ISSUE THREAD

**Issue by geetduggal** [appc/docker2aci#198]
Hi @yifan-gu , @jonboulle 

Related to: https://github.com/appc/docker2aci/issues/122 , @mlin and I noticed that there appears to be an issue where the manifest file is missing ENTRYPOINT and CMD annotations when newer versions of Docker are used to build images and those images are subsequently posted to Dockerhub.

An example to reproduce this issue is:

Using two versions of Docker (in our case we used 1.6.2 and 1.11.2, the current versions on Ubuntu 14.04 and 16.04 respectively):

- Build a simple Docker image using both versions of Docker:

```
echo "FROM ubuntu:14.04
ENTRYPOINT ls" | docker build -
```

- Push each image to Dockerhub (in our example we have geetduggal/docker2aci-entrypoint-issue and dnamlin/docker2aci-entrypoint-issue built with Docker versions 1.6.2 and 1.11.2 respectively)

- Run `docker2aci docker://<repo>/<imagename>` on each of these images

We noticed that the manifest file for image associated with dnamlin (Docker version 1.11.2) did not contain the entrypoint annotation while the image associated with geetduggal (Docker version 1.6.2) does.

Consequently, we cannot emulate the ENTRYPOINT + CMD user experience as discussed in the original issue.

If we manually pull and save the image from Dockerhub (using `docker pull` and `docker save`), then the annotation is preserved.   Therefore it appears that something in the interaction between docker2aci and Dockerhub is causing this missing annotation and that's about as far as we have narrowed it down to.

**Comment by iaguis** [comment]
It seems the older image uses Docker API v2.1 and the newer v2.2.

**Comment by geetduggal** [comment]
Excellent.  Thanks!

**Comment by jonboulle** [comment]
@iaguis do we need a rkt bump? :grin:
