### ISSUE TITLE
docker2aci should retain extended attributes when converting images

### ISSUE THREAD

**Issue by lucab** [appc/docker2aci#202]
As reported in https://github.com/coreos/rkt/issues/3179, it looks like during docker2aci capabilities set on file (via xattrs) are getting lost.
They should instead be carried on to ACI images.

**Comment by s-urbaniak** [comment]
I am pretty confident, that the error is not in docker2aci itself, but in the ACI extraction logic in rkt.

In docker2aci we are preserving the [tar#Header.Xattr](https://godoc.org/archive/tar#Header) while converting the docker layer tar header to the ACI tar header as per [1].

I verified this on the test docker image reported in https://github.com/coreos/rkt/issues/3179, converted it using docker2aci, and the generated ACI file retained the xattr attributes.

[1] https://github.com/appc/docker2aci/blob/master/lib/internal/internal.go#L603

**Comment by jonboulle** [comment]
Should we close this one out then?
