### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by daviddelikat** [appc/docker2aci#231]
I'm building on debian and I get this message:
```
gopath/src/github.com/appc/docker2aci/lib/internal/internal.go:41:2: cannot find package "github.com/appc/spec/aci" in any of:
	/usr/lib/go/src/pkg/github.com/appc/spec/aci (from $GOROOT)
	/home/dav/_/docker2aci/gopath/src/github.com/appc/spec/aci (from $GOPATH)
```
along with a bunch more similar messages.  ( I can post the rest of them if it would be helpful )

also, let me know if I need to provide any more info ( I'm not familiar with golang... )

**Comment by jonboulle** [comment]
@daviddelikat how are you building? Are you using a copy of the source checked out from master, or somewhere else?

**Comment by daviddelikat** [comment]
I followed the direction in the README.  ( git clone <>; cd <> ; ./build.sh )

**Comment by jonboulle** [comment]
@daviddelikat ah, what version of Go are you using? something <1.6 I guess? We rely on the vendoring support: https://golang.org/doc/go1.6#go_command

**Comment by daviddelikat** [comment]
correct, I've got 1.3.3; I'll have to find the latest version.
thanks for your help
