### ISSUE TITLE
docker2aci should work with local docker images

### ISSUE THREAD

**Issue by alban** [appc/docker2aci#32]
Currently docker2aci can only take a docker image from a registry (through the network).

After building a Docker image locally from a Dockerfile, it is inconvenient to have to upload it to a registry before being able to convert it to an aci with docker2aci.

Instead, it would be great if docker2aci could work on local files produced by docker-save.

**Comment by jonboulle** [comment]
Welp, absolutely, for some reason I thought this was already implemented

**Comment by jonboulle** [comment]
I'm confused on the status of this, is there a branch floating around?

**Comment by iaguis** [comment]
Yes: https://github.com/endocode/docker2aci/commit/9780d10f8e2b54c7e441b6c9c264c80937035ec0

It still needs some love though
