### ISSUE TITLE
docker2aci: create ACI from Dockerfile

### ISSUE THREAD

**Issue by jonboulle** [appc/docker2aci#4]
It would be nice to be able to take a `Dockerfile` and convert it to an ACI. This should be semantically equivalent to running `docker build` and then using `docker2aci` on the resulting image.

Hopefully this could leverage the work done by @mcuadros in https://github.com/appc/spec/pull/51 (originally https://github.com/mcuadros/rocketizer) - this issue should obviate that one when implemented.

**Comment by philips** [comment]
I am a bit on the fence having thought this through some more. I can see it being somewhat useful but we could only support a super limited subset of the grammar. It seems better to just leave this task to the docker engine unless someone wants to create something that operates on a chroot and spits out an ACI on every line or something.

**Comment by jonboulle** [comment]
Yes, this was originally a somewhat speculative feature idea but I am also unconvinced it would necessarily be wise; we should probably just defer to the Docker engine for the build process and focus on the conversion from the built image.

**Comment by jonboulle** [comment]
Let's stick to letting the Docker engine do its thing and focus on appropriately converting the output images.
