### ISSUE TITLE
Volumes are ignored during conversion

### ISSUE THREAD

**Issue by slallema** [appc/docker2aci#40]
The Volumes mount points are ignored so I need to patch the resulting ACI with correct mount points.
The problem is that docker doesn't name the volumes so I don't know if docker2aci should set arbitrarily a name or interactively asking for the name of each volume.

**Comment by iaguis** [comment]
Maybe we can generate a name based on the path, for example  `/var/lib/www -> volume-var-lib-www`. Would that help?

**Comment by slallema** [comment]
That seems fine to me. We can also escape the dashes to avoid collisions : 
```/var/www/a => volume-var-www-a```
```/var/www-a => volume-var-www--a```

**Comment by iaguis** [comment]
Actually, [slashes are allowed](https://github.com/appc/spec/blob/132244a30a16d49f106b9983509e65e49d5c124e/schema/types/acname.go#L12) so we could name them `volume-/var/www-a`. I plan to use [SanitizeACName](https://github.com/appc/spec/blob/132244a30a16d49f106b9983509e65e49d5c124e/schema/types/acname.go#L121) so every not-valid char is replaced with a dash, I guess it should be fine.

**Comment by iaguis** [comment]
I filed #43.

The only problem I see is discoverability: if the user doesn't know the volumes' paths and the way docker2aci converts them there's no way for her to know the the mountPoints' names without extracting and reading the manifest (or using `actool cat-manifest`).

Maybe we should output the generated volumes after the conversion? Thoughts?

**Comment by rimusz** [comment]
output the generated volumes after the conversion really would help, without needs of using `actool cat-manifest`

**Comment by iaguis** [comment]
I updated #43 to print the generated volumes. This only works when running the docker2aci command, it doesn't print anything if it's used as a library.

**Comment by rimusz** [comment]
@iaguis cool, thanks for that

**Comment by rimusz** [comment]
@iaguis so when #43 is merged it should allow in the same --volume "volume-/var/tmp" for docker2aci and rot, right?

But what about `rkt run some docker_image` which has no volume, e.g. in docker way we do:
docker run web1 -p 80:80 -v /home/core/share/nginx/html:/usr/share/nginx/html nginx:latest

How then we can use volumes in rkt?

**Comment by iaguis** [comment]
Then you'll have to wait for coreos/rkt#761 to get resolved :smile:

**Comment by rimusz** [comment]
@iaguis is this one way: rkt run --volume mount=/var/lib/postgresql/data,kind=host,source=/opt/data docker://posgres:9.4 going to work from rkt?

**Comment by jonboulle** [comment]
Perhaps not that exact syntax but something similar

**Comment by rimusz** [comment]
@jonboulle That syntax will for the chapter's 1st draft.
I will change it to the proper one when we have it release

**Comment by iaguis** [comment]
Closed #40 via #43
