### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by mischief** [appc/docker2aci#48]
it would be nice to have a tagged release with a version number for packaging.

**Comment by jonboulle** [comment]
docker2aci should be versioned against the appc spec.
/cc @iaguis

**Comment by iaguis** [comment]
> docker2aci should be versioned against the appc spec.
> /cc @iaguis

I think we changed our minds here (https://github.com/appc/docker2aci/pull/128#issuecomment-193213882)

**Comment by lucab** [comment]
docker2aci is being versioned (separately from appc/spec), closing.
