### ISSUE TITLE
use ContainerApplicationGenericLabels for VCS information

### ISSUE THREAD

**Issue by jonboulle** [appc/docker2aci#59]
The ContainerApplicationGenericLabels  effort is looking to standardise labels for containers - we should sync up wherever possible, e.g. https://github.com/projectatomic/ContainerApplicationGenericLabels/pull/12/files

**Comment by iaguis** [comment]
You mean adding these labels pointing to the docker2aci repo?

**Comment by jonboulle** [comment]
Oops, I filed this against the wrong project, sorry (supposed to be`go2aci`)
