### ISSUE TITLE
support authentication to a registry

### ISSUE THREAD

**Issue by philips** [appc/docker2aci#7]
- [x] Reading a .dockercfg
- [ ] Taking in configuration via env variables and command line
- [x] Support being passed credentials when used as a library

**Comment by iaguis** [comment]
I added .dockercfg auth in #23

Are env variables and/or command line authentication needed? If the user calls `docker login SERVER` before everything should work. I think this is enough.

**Comment by iaguis** [comment]
Hmmm... Running
```
sudo rkt run docker://repo/image
```

with #23 to fetch an image that needs authentication won't work because it will try to find `/root/.dockercfg`. You'd need to preserve the environment:

```
sudo -E rkt docker://repo/image
```

Maybe env variables make sense.

**Comment by jonboulle** [comment]
docker2aci should also support being passed in credentials when used as a library

**Comment by iaguis** [comment]
Should we close this or do we want to support env variables and command line?

**Comment by jonboulle** [comment]
I am fine with just .dockercfg, will defer to @philips if he has stronger opinions

**Comment by jonboulle** [comment]
Let's revisit if necessary.
