### ISSUE TITLE
some docker2aci generated images doesn't have an arch label.

### ISSUE THREAD

**Issue by sgotti** [appc/docker2aci#74]
```
docker2aci docker://busybox
Downloading cf2616975b4a: [====================================] 32 B/32 B
Downloading 6ce2e90b0bc7: [====================================] 1.15 MB/1.15 MB
Downloading 8c2e06607696: [====================================] 32 B/32 B

Generated ACI(s):
busybox-latest.aci
```
```
tar xvfO busybox-latest.aci manifest 
manifest
{"acKind":"ImageManifest","acVersion":"0.5.1","name":"busybox","labels":[{"name":"version","value":"latest"},{"name":"os","value":"linux"}],"app":{"exec":["/bin/sh"],"user":"0","group":"0"},"annotations":[{"name":"authors","value":"Jérôme Petazzoni \u003cjerome@docker.com\u003e"},{"name":"created","value":"2015-04-17T22:01:13Z"}]}
``` 

This is problably due to an empty layerData.Architecture (probably before docker supported archs different than amd64).

In future with coreos/rkt#1167 stage0 will refuse to execute it due to missing arch.

One possible solution will be to set os=Linux if os is empty and arch=amd64 if arch is empty.

**Comment by jonboulle** [comment]
> One possible solution will be to set os=Linux if os is empty and arch=amd64 if arch is empty.

Seems reasonable, particularly if we could verify that Docker does the same or equivalent..?

**Comment by iaguis** [comment]
> This is problably due to an empty layerData.Architecture (probably before docker supported archs different than amd64).

Actually, that was a bug on docker2aci. We were ignoring the arch field :flushed: appc/docker2aci#75

**Comment by sgotti** [comment]
@iaguis great! Thanks!
