### ISSUE TITLE
parallelise layer retrieval

### ISSUE THREAD

**Issue by jonboulle** [appc/docker2aci#83]
Fetching and converting an image is really slow when every layer is downloaded in serial.

**Comment by runcom** [comment]
since the layers ordered list is maintained (both in memory and in the manifest) it should be easy to run the layers' download in goroutines

**Comment by runcom** [comment]
however access to the stdout/err isn't serialized for the progress output :P

**Comment by jonboulle** [comment]
great, looking forward to it!

**Comment by jonboulle** [comment]
Closing in favour of #146
