### ISSUE TITLE
handle hard links and whiteouts in different layers

### ISSUE THREAD

**Issue by alban** [appc/docker2aci#98]
Bug initially reported on https://github.com/coreos/rkt/issues/1653: if a Docker image has the hard links `/LINK-A` and `/LINK-B` in the first layer but `/LINK-A` gets deleted in the second layer, `docker2aci` generates a squashed tarball that contains only `/LINK-B` as a dangling reference, so the tarball cannot be extracted.

To produce the image [docker://albanc/busybox-hardlinks](https://hub.docker.com/r/albanc/busybox-hardlinks/), I followed the steps:
```
# docker run -ti busybox
(container)# touch /LINK-A
(container)# ln /LINK-A /LINK-Z
(container)# exit
# docker commit $container_id
# docker run -ti $container_id
(container)# rm -f /LINK-A
(container)# exit
# docker commit $container_id_2 albanc/busybox-hardlinks
$ docker2aci docker://albanc/busybox-hardlinks
$ tar xf albanc-busybox-hardlinks-latest.aci
tar: rootfs/LINK-Z: Cannot hard link to ‘rootfs/LINK-A’: No such file or directory
```

**Comment by alban** [comment]
/cc @josephschorr @jakedt

The same bug exists in the quay.io Docker image squasher. I uploaded my [busybox-hardlinks Docker image](https://hub.docker.com/r/albanc/busybox-hardlinks/) into [quay.io/alban/busybox-hardlinks](https://quay.io/repository/alban/busybox-hardlinks) and then downloaded a squashed image from [the quay.io web interface](https://quay.io/repository/alban/busybox-hardlinks?tab=tags) (click on Fetch tag / Squashed Docker image). Then, the image also has a dangling hard link, so it cannot be extracted:

```
$ tar tvf /tmp/quay.io-alban-busybox-hardlinks-latest.squash.aci | grep LINK
hrw-r--r-- 0/0               0 2015-10-21 23:26 rootfs/LINK-Z link to rootfs/LINK-A
$ tar xf /tmp/quay.io-alban-busybox-hardlinks-latest.squash.aci
tar: rootfs/LINK-Z: Cannot hard link to ‘rootfs/LINK-A’: No such file or directory
```

**Comment by josephschorr** [comment]
@alban: I just tried this locally without any errors. I pulled the image from DockerHub, pushed to my local Quay, then squash pulled image. Do you have another repro case I can try?

**Comment by alban** [comment]
@josephschorr : there is also the image https://hub.docker.com/r/zopyx/xmldirector-plone/ but given its size (854MB), it is easier to try with my image https://hub.docker.com/r/albanc/busybox-hardlinks/ (1MB). I could reproduce the issue just now. I think I mixed the explanation in my comment above between downloading the aci and the Docker squashed image. I can see the problem when using: 

```
$ curl -L -f https://alban+squashedrobot:xxxxx@quay.io/c1/squash/alban/busybox-hardlinks/latest 2>/dev/null | sudo docker load
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: link /LINK-A /LINK-Z: no such file or directory
```

**Comment by josephschorr** [comment]
Hmm, I tried that image. Will try again tomorrow.
